### ISSUE TITLE
Spacing on the right of Avatar in Navbar

### ISSUE THREAD

**Issue by vighnesh192** [vighnesh192/project-showcase-client#1]
Avatar and Top Creators card must be aligned in the same line (as marked in Red in the image below) :-
<br>
![avatar_margin](https://user-images.githubusercontent.com/64535868/123551847-2e2f1780-d791-11eb-8658-c6bdfd5366cf.jpg)

**Comment by godwin-morwin** [comment]
hi , can i work on this

**Comment by vighnesh192** [comment]
> Hello, ya sure! I'll assign it to you.

**Comment by vighnesh192** [comment]
> hi , can i work on this

Hi @Godwindaniel10.  Ya sure, I'll assign it to you.

**Comment by godwin-morwin** [comment]
thanks. on it ...

**Comment by godwin-morwin** [comment]
@vighnesh192 , after running ( npm start ) , this was what was running on the server ( localhost:3000 ), and there are errors displayed in the terminal

![errorn](https://user-images.githubusercontent.com/54848535/123562397-858bb280-d7a6-11eb-9277-9dc71ff760d0.JPG)

**Comment by vighnesh192** [comment]
@Godwindaniel10 The proxy error has occurred because the backend hasn't been set up. Here's the link to the repo https://github.com/vighnesh192/project_showcase_server

**Comment by godwin-morwin** [comment]
Aiit

**Comment by vighnesh192** [comment]
Hi @Godwindaniel10, are you still working on it? Please let me know.

**Comment by godwin-morwin** [comment]
hi @vighnesh192 , sorry i didn't get back to you concerning this issue, am so so sorry for that. 

i still cant figure it out. it's best you assign the project to anyone else. and I am a bit overwhelmed at the moment.

**Comment by vighnesh192** [comment]
Ohh.. that's absolutely fine! Thanks for letting me know. :)

**Comment by godwin-morwin** [comment]
sorry, i should have let you know earlier , but got a lot going through my head.

**Comment by vighnesh192** [comment]
Heyy..you don't need to worry about it, that's completely fine!

**Comment by ehteshaxm** [comment]
Hey, Can I work on this?

**Comment by vighnesh192** [comment]
Ya sure @cadmaus, I'll assign it to you. Thank you!

**Comment by ehteshaxm** [comment]
Hey, @vighnesh192 Login functionality is not working so, I am unable to check the avatar

**Comment by vighnesh192** [comment]
I'm sorry @cadmaus, I should've let you known about this earlier.
You can refer this:- https://github.com/vighnesh192/project-showcase-client/pull/2#pullrequestreview-696285246
